<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href=" ">Inst'grem (eng. Bad copy)</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="../">Welcome page</a></li>
            <li class="active"><a href="/login">Sign in</a></li>
            <li><a href="/registration">Registration</a></li>
        </ul>
    </div>
</nav>

<div style="text-align: center">
<form method="post" action="/login/signin">
    Username:<br>
    <input type="text" name="username"><br>
    Password:<br>
    <input type="password" name="password"><br><br>
    <input class="btn btn-info" type="submit" name="signInButton" value="Sign In">
    <br>
    <br>
    <a href="/registration">Go to registration</a> <br>
    <a href="/">Go to welcome page</a>
</form>
</div>