<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand">Inst'grem (eng. Bad copy)</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="../">Welcome page</a></li>
            <li><a href="/login">Sign in</a></li>
            <li class="active"><a href="/registration">Registration</a></li>
        </ul>
    </div>
</nav>

<div style="text-align: center">
<form method="post" action="/registration/signup">
    Username:<br>
    <input type="text" name="username"><br>
    Email:<br>
    <input type="text" name="email"><br>
    Password:<br>
    <input type="password" name="password"><br>
    Repeat password:<br>
    <input type="password" name="repeatPassword"><br><br>
    <input class="btn btn-info" type="submit" name="signUpButton" value="Sign Up">
    <br>
    <br>
    <a href="/login">Go to login</a><br>
    <a href="/">Go to welcome page</a>
</form>
</div>